### ISSUE TITLE
Display errors to the user in the UI

### ISSUE THREAD

**Issue by ar-jan** [unipv-larl/udeasy#5]
A colleague (working on a Mac) had trouble opening a `.conllu` file and at first it wasn't clear why -- after loading a file and clicking "Confirm" nothing happened. After starting the binary manually with console output we found the reason:

udeasy[33022:805400] +[CATransaction synchronize] called within transaction
Traceback (most recent call last):
  File "home.py", line 55, in show_nodes_panel
  File "valideasy.py", line 68, in validate
  File "udapi/core/document.py", line 35, in __init__
  File "udapi/core/document.py", line 68, in load_conllu
  File "udapi/core/basereader.py", line 161, in process_document
  File "udapi/core/basereader.py", line 110, in try_fast_load
  File "udapi/core/basereader.py", line 68, in next_filehandle
  File "udapi/core/files.py", line 130, in next_filehandle
FileNotFoundError: [Errno 2] No such file or directory: '/Users/USERNAME/Library/CloudStorage/OneDrive/Corpus'
udeasy[33022:805400] +[CATransaction synchronize] called within transaction

Presumably the cloud storage is not a local filesystem; after moving the corpus files elsewhere things worked OK. It would be good to have errors displayed in the main UI.

**Comment by bavagliladri** [comment]
Thank you, I should certainly signal errors in the main UI

**Comment by bavagliladri** [comment]
Errors should be showed in the UI now
